### PR TITLE
Fix ci

### PR DESCRIPTION
**Pull request by Xynnn007**

### CODE REVIEW

**Comment by Xynnn007** [comment]
Hey @mkulke , to compile `az-cvm-vtpm` requires `tss2-sys>=2.3.3` while on ubuntu only `v2.3.2` could be got via `apt`. link

Could you help to resolve this?

**Comment by mkulke** [comment]
> Hey @mkulke , to compile `az-cvm-vtpm` requires `tss2-sys>=2.3.3` while on ubuntu only `v2.3.2` could be got via `apt`. https://github.com/confidential-containers/image-rs/actions/runs/5330529151/jobs/9657289027?pr=163
> 
> Could you help to resolve this?

Are we able to bump ubuntu to 22.04? The Rust libtss wrapper won't compile ootb on older versions of libtss2. I made it compile on ubuntu 20.04 by compiling/installing a tpm2-tss tarball manually, but maybe we don't need this.

**Comment by Xynnn007** [comment]
> Are we able to bump ubuntu to 22.04? The Rust libtss wrapper won't compile ootb on older versions of libtss2. I made it compile on ubuntu 20.04 by compiling/installing a tpm2-tss tarball manually, but maybe we don't need this.

Let me take a try

**Comment by Xynnn007** [comment]
I test locally and new version of `tss` stack was installed, but ubuntu 22.04 GH Runner does not

**Comment by mkulke** [comment]
> I test locally and new version of `tss` stack was installed, but ubuntu 22.04 GH Runner does not

you need to explicitly install it: `sudo apt-get install -y libtss2-tctildr0`, specifically

**Review by mkulke — APPROVED** [review]
LGTM

**Review by sameo — APPROVED** [review]

**Pull request merged**
